### ISSUE TITLE
Anxious to try out the code :)

### ISSUE THREAD

**Issue by Jordy-VL** [mijungkim-rakuten/multi-scale-cell-based#1]

**Comment by logan-markewich** [comment]
I'm excited to try training on DocVQA :) I hope the license will be more open than LayoutLMV2/3

**Comment by mijungkim-rakuten** [comment]
Hi, @logan-markewich,

The github link has been changed to here: https://github.com/rakutentech/Document-understanding

Please check this out.

**Comment by logan-markewich** [comment]
@mijungkim-rakuten thank you!! 🙏🏻
